[meta]
name     = "Server-Game Scoreboard"
author   = "XertroV"
category = "TMX"
version  = "1.0.1"
siteid   = 564

[script]
#__DEFINES__
dependencies = ["NadeoServices", "BetterRoomManager"]
optional_dependencies = ["tmx-together"]
