[meta]
name     = "TMX Together"
author   = "XertroV"
category = "TMX"
version  = "0.1.3"

[script]
#__DEFINES__
dependencies = ["NadeoServices", "MLHook", "MLFeedRaceData"]
optional_dependencies = ["BetterChat",
    "BetterRoomManager", "better-room-manager-dev",
    "mapinfo", "map-info-dev"
    ]
