[meta]
name     = "TMX Together"
author   = "XertroV"
category = "TMX"
version  = "0.1.0"

[script]
#__DEFINES__
dependencies = ["NadeoServices"]
optional_dependencies = ["BetterRoomManager", "better-room-manager-dev"]
