[meta]
name     = "TMX Together"
author   = "XertroV"
category = "TMX"
version  = "0.1.14"
siteid   = 442

[script]
#__DEFINES__
dependencies = ["NadeoServices", "MLHook", "MLFeedRaceData", "BetterRoomManager"]
optional_dependencies = ["BetterChat",
    "mapinfo", "map-info-dev"
    ]
module = "TmxTogether"
exports = ["ExportCode.as"]
